language: android
jdk: oraclejdk8

dist: xenial

android:
  components:
    - platform-tools
    - tools
    - build-tools-29.0.2
    - android-29
    - extra-android-m2repository

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;29.0.3"
  - export LANG=en_US.UTF-8

stages:
  - check
  - test
  - deploy

jobs:
  include:
    - stage: check
      name: "Analysis"
      script: ./gradlew detektAll
    - stage: test
      name: "Unit Tests"
      script: ./gradlew test
    - stage: deploy
      name: "Publishing"
      if: (branch =~ ^(master|^release.*)$ AND tag IS present) OR branch = develop
      script: ./gradlew fullRollout
      deploy:
        provider: releases
        api_key: "$GITHUB_TOKEN"
        file_glob: true
        file: build/artifacts/**/*
        skip_cleanup: true
        on:
          tags: true
